# -*- coding: utf-8 -*-
"""Analysis of Global COVID-19 Pandemic Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4y0ytc8-oqU4fhMgEizUDqlxu9v5jE5

### Running R code in a Python Notebook using `rpy2`

To run R code directly within a Python notebook, you can use the `rpy2` library, which allows for seamless interoperability between Python and R. Follow these steps:
"""

# Commented out IPython magic to ensure Python compatibility.
# Load the rpy2.ipython extension
# %load_ext rpy2.ipython

"""Once the extension is loaded, you can use the `%%R` magic command at the beginning of a cell to indicate that the code within that cell should be executed as R code."""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages(c("httr", "rvest", "xml2"))
# 
# library(httr)
# library(rvest)
# library(xml2)
# 
# print("R packages installed and loaded successfully!")

"""This approach is useful when you need to leverage specific R packages or functions within your Python-centric workflow. Alternatively, if your entire notebook is intended to be in R, you should change the runtime type as previously instructed."""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# url <- "https://en.wikipedia.org/wiki/COVID-19_testing"
# 
# response <- GET(url)
# 
# # Check status code
# status_code(response)

"""#Task 2: Extract COVID-19 Testing Data Table from the Wiki HTML Page

#Get HTML Content
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# html_content <- content(response, as = "text", encoding = "UTF-8")
# 
# cat(substr(html_content, 1, 500))

"""#Get the Root HTML Node from the HTTP Response"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# root_html <- read_html(html_content)
# 
# root_html

"""#Get All Table Nodes from the Root HTML"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# tables <- html_elements(root_html, "table")
# 
# length(tables)

"""#Inspect Available Tables"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# for(i in seq_along(tables)){
#   cat("\nTable:", i, "\n")
#   print(html_table(tables[[i]], fill = TRUE)[1:5, ])
# }

"""Select the COVID-19 Testing Data Table

Wikipedia pages may contain multiple tables. Choose the relevant table.

For example:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_table <- html_table(tables[[3]], fill = TRUE)
# 
# head(covid_table)

"""#Read the Table Node and Convert It Into a Data Frame"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df <- as.data.frame(covid_table)
# 
# head(covid_df)

"""#Print the Data Frame for Review"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# print(covid_df)
# 
# str(covid_df)
# 
# summary(covid_df)

"""#Clean Column Names"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# colnames(covid_df) <- make.names(colnames(covid_df))
# 
# names(covid_df)

"""#Basic Exploratory Analysis

Number of Rows and Columns
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# dim(covid_df)

"""#Missing Values"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# colSums(is.na(covid_df))

"""#First 10 Records"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# head(covid_df, 10)

"""#Project Outcome

Retrieved a live COVID-19 Wikipedia page using an HTTP GET request.
Parsed HTML content into a structured document.


Extracted table data from the webpage.
Converted the table into an R data frame.
Performed preliminary data inspection and exploratory analysis.


This workflow demonstrates web scraping, HTTP requests, HTML parsing, and data extraction skills commonly used in data analytics and data science projects.

#TASK 3: Pre-process and export the extracted data frame

#Step 1: Inspect the Data
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # View first few rows
# head(covid_df)
# 
# # Check structure
# str(covid_df)
# 
# # Summary statistics
# summary(covid_df)

"""#Step 2: Rename Columns

Clean column names by removing spaces and special characters.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# names(covid_df) <- make.names(names(covid_df))
# 
# # View updated column names
# names(covid_df)

"""#Step 3: Remove Duplicate Rows"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df <- covid_df[!duplicated(covid_df), ]
# 
# # Number of rows after removing duplicates
# nrow(covid_df)

"""#Step 4: Handle Missing Values

Check for missing values:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# colSums(is.na(covid_df))

"""#Replace missing values with NA:"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df[covid_df == ""] <- NA

"""#Remove rows with excessive missing values:"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df <- na.omit(covid_df)

"""#Step 7: Convert Numeric Columns

Identify numeric columns and convert them.

Example:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# numeric_cols <- c("Tests",
#                   "Positive",
#                   "Tests.per.million")
# 
# for(col in numeric_cols){
#   if(col %in% names(covid_df)){
#     covid_df[[col]] <- as.numeric(covid_df[[col]])
#   }
# }

"""#Check structure:"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# str(covid_df)

"""#Step 8: Standardize Country Names

Remove extra spaces:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df$Country.or.region <- trimws(covid_df$Country.or.region)

"""#Convert to title case:"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df$Country.or.region <- tools::toTitleCase(
#   tolower(covid_df$Country.or.region)
# )

"""#Step 9: Create Derived Metrics

Positivity Rate
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Convert 'Tested', 'Confirmed(cases)', and 'Confirmed..population..' to numeric, handling commas
# covid_df$Tested <- as.numeric(gsub(",", "", covid_df$Tested))
# covid_df$Confirmed.cases. <- as.numeric(gsub(",", "", covid_df$Confirmed.cases.))
# covid_df$Confirmed..population.. <- as.numeric(gsub(",", "", covid_df$Confirmed..population..))
# 
# # Calculate Positivity_Rate
# covid_df$Positivity_Rate <- (covid_df$Confirmed.cases. / covid_df$Tested) * 100

"""#Tests per Positive Case"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df$Tests_Per_Case <- covid_df$Tested / covid_df$Confirmed.cases.

"""#Step 10: Sort Data

Highest testing countries:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# covid_df <- covid_df[
#   order(covid_df$Tested, decreasing = TRUE),
# ]

"""#View top countries:"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# head(covid_df, 10)

"""#Step 11: Export Cleaned Dataset to CSV"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# write.csv(
#   covid_df,
#   "covid_testing_cleaned.csv",
#   row.names = FALSE
# )

"""#Step 12: Verify Export"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# exported_data <- read.csv(
#   "covid_testing_cleaned.csv"
# )
# 
# head(exported_data)

"""#Outcome

After preprocessing, the dataset is:

- Cleaned of duplicates and missing values.
- Free of Wikipedia reference tags.
- Converted to appropriate numeric data types.
- Enhanced with new analytical metrics (Positivity Rate and Tests per Case).
- Exported as covid_testing_cleaned.csv for further EDA, visualization, or machine learning tasks.

#TASK 4: Get a subset of the extracted data frame

1. Display the First 10 Rows
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# head(covid_df, 10)

"""#2. Select Specific Columns

Suppose you only want the country name and total tests:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# names(covid_df)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# colnames(covid_df) <- make.names(colnames(covid_df))
# names(covid_df)

"""#3. Get Top 10 Countries by Number of Tests"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# top10_tests <- covid_df[order(covid_df$Tested, decreasing = TRUE), ]
# 
# top10_tests <- head(top10_tests, 10)
# 
# top10_tests

"""#4. Filter Countries with More Than 1 Million Tests"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# high_testing <- subset(covid_df, Tested > 1000000)
# 
# head(high_testing)

"""#5. Select Rows and Columns Together"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# country_tests <- covid_df[
#   covid_df$Tested > 1000000,
#   c("Country.or.region", "Tested")
# ]
# 
# head(country_tests)

"""#6. Extract Specific Countries

For example, USA, India, and Brazil:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# selected_countries <- subset(
#   covid_df,
#   Country.or.region %in% c("United States", "India", "Brazil")
# )
# 
# selected_countries

"""#7. Countries with Highest Positivity Rate"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# top_positive <- covid_df[
#   order(covid_df$Positivity_Rate, decreasing = TRUE),
# ]
# 
# head(top_positive, 10)

"""#8. Create a Random Sample"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# set.seed(123)
# 
# sample_data <- covid_df[
#   sample(nrow(covid_df), 10),
# ]
# 
# sample_data

"""#9. Using dplyr (Alternative Method)"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# covid_subset <- covid_df %>%
#   select(Country.or.region, Tested, Positivity_Rate) %>% # Corrected 'Tests' to 'Tested'
#   arrange(desc(Tested)) %>% # Corrected 'Tests' to 'Tested'
#   slice(1:10)
# 
# covid_subset

"""#Export the Subset"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# write.csv(
#   covid_subset,
#   "covid_subset.csv",
#   row.names = FALSE
# )

"""#Expected Outcome

The resulting subset contains:

- Country/Region
- Total Tests
- Positive Cases
- Positivity Rate

for the top 10 countries by testing volume, making it easier to perform focused analysis and visualization in later tasks.

#TASK 5: Calculate worldwide COVID testing positive ratio


The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using confirmed cases / tested cases

#Step 1: Inspect the Data

First, ensure the relevant columns are numeric.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# str(covid_df)

"""#Step 2: Calculate Total Tested Cases Worldwide"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# total_tested <- sum(covid_df$Tested, na.rm = TRUE)
# 
# total_tested

"""#Step 3: Calculate Total Confirmed Cases Worldwide"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# total_confirmed <- sum(covid_df$Confirmed.cases., na.rm = TRUE)
# 
# total_confirmed

"""#Step 4: Calculate Worldwide Positive Ratio"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# positive_ratio <- total_confirmed / total_tested
# 
# positive_ratio

"""#Step 5: Convert to Percentage"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# positive_percentage <- positive_ratio * 100
# 
# positive_percentage

"""#Step 6: Display Results"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cat("Worldwide COVID Testing Statistics\n")
# cat("-----------------------------------\n")
# cat("Total Tested Cases:", format(total_tested, big.mark=","), "\n")
# cat("Total Confirmed Cases:", format(total_confirmed, big.mark=","), "\n")
# cat("Worldwide Positive Ratio:", round(positive_ratio, 4), "\n")
# cat("Worldwide Positive Percentage:", round(positive_percentage, 2), "%\n")

"""#Alternative Solution Using dplyr"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# covid_summary <- covid_df %>%
#   summarise(
#     Total_Tested = sum(Tested, na.rm = TRUE),
#     Total_Confirmed = sum(Confirmed.cases., na.rm = TRUE) # Corrected column name
#   ) %>%
#   mutate(
#     Positive_Ratio = Total_Confirmed / Total_Tested,
#     Positive_Percentage = Positive_Ratio * 100
#   )
# 
# covid_summary

"""#Interpretation

- A positive ratio of 0.10 means approximately 1 out of every 10 tests returned positive.
- A positive percentage of 10% indicates the proportion of all COVID-19 tests that resulted in confirmed cases worldwide.
- Lower positivity rates generally indicate broader testing coverage, while higher rates may suggest under-testing or widespread transmission.

#TASK 6: Get a country list which reported their testing data


The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

#Step 1: Extract the Country Column

Assuming the data frame contains a column named Country.or.region:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# country_list <- covid_df$Country.or.region

"""#Step 2: Remove Missing Values"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# country_list <- na.omit(country_list)

"""#Step 3: Remove Duplicate Countries"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# country_list <- unique(country_list)

"""#Step 4: Sort the Country List Alphabetically"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# country_list <- sort(country_list)

"""#Step 5: Display the Country List"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# print(country_list)

"""#Step 6: Count the Number of Reporting Countries"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# num_countries <- length(country_list)
# 
# cat("Number of countries reporting testing data:", num_countries)

"""#Create a Data Frame of Reporting Countries"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# countries_df <- data.frame(
#   Country = country_list
# )
# 
# head(countries_df)

"""#Export the Country List"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# write.csv(
#   countries_df,
#   "reporting_countries.csv",
#   row.names = FALSE
# )

"""#Expected Outcome

The resulting dataset:

- Contains one row per country/region that reported COVID-19 testing data.

- Has no duplicates or missing values.

- Is sorted alphabetically for easier lookup.

- Can be exported as reporting_countries.csv for further analysis or visualization.

#TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with United

#Step 1: Review the Country List

Assume you already have:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# country_list <- covid_df$Country.or.region

"""#Step 2: Use a Regular Expression

The regex pattern:
"""

"^United"

"""#Step 3: Find Matching Countries"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# united_countries <- grep(
#   "^United",
#   country_list,
#   value = TRUE
# )
# 
# united_countries

"""Alternative Using grepl()"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# united_countries <- country_list[
#   grepl("^United", country_list)
# ]
# 
# united_countries

"""#Step 4: Sort the Results"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# united_countries <- sort(unique(united_countries))
# 
# print(united_countries)

"""#Step 5: Count the Matches"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cat(
#   "Number of countries starting with 'United':",
#   length(united_countries)
# )

"""#Expected Output

Depending on the Wikipedia data, you may see:

[1] "United Arab Emirates"

[2] "United Kingdom"

[3] "United States"

Countries starting with 'United': 3

TASK 8: Pick two countries you are interested, and then review their testing data


The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select country, confirmed, confirmed-population-ratio columns

#Step 1: Choose Two Countries

For example:

United States

India

You can replace these with any two countries of interest.

#Step 2: Select the Required Columns
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# selected_data <- covid_df[
#   covid_df$Country.or.region %in% c("United States", "India"),
#   c("Country.or.region",
#     "Confirmed.cases.",
#     "Confirmed..population..")
# ]
# 
# selected_data

"""#Step 3: Using dplyr (Alternative)"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# selected_data <- covid_df %>%
#   filter(Country.or.region %in%
#            c("United States", "India")) %>%
#   select(
#     Country.or.region,
#     Confirmed.cases.,
#     Confirmed..population..
#   )
# 
# selected_data

"""#Step 4: Display Results"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# print(selected_data)

"""#Step 5: Compare the Two Countries"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# usa_ratio <- selected_data$Confirmed..population..[
#   selected_data$Country.or.region == "United States"
# ]
# 
# india_ratio <- selected_data$Confirmed..population..[
#   selected_data$Country.or.region == "India"
# ]
# 
# cat("US Confirmed/Population Ratio:", usa_ratio, "\n")
# cat("India Confirmed/Population Ratio:", india_ratio, "\n")

"""#Interpretation

After extracting the two rows:

Confirmed Cases shows the total number of reported COVID-19 infections.
Confirmed Population Ratio indicates the proportion of the population that has been confirmed infected.

For example:

A ratio of 0.31 means approximately 31% of the population had confirmed COVID-19 cases.
A ratio of 0.03 means approximately 3% of the population had confirmed COVID-19 cases.

This comparison helps evaluate the relative impact of COVID-19 across countries while accounting for differences in population size.

#TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

#Step 1: Retrieve the Two Countries' Data

Using the same countries selected in Task 8 (e.g., United States and India):
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# comparison_df <- covid_df[
#   covid_df$Country.or.region %in% c("United States", "India"),
#   c("Country.or.region",
#     "Confirmed.cases.",
#     "Confirmed..population..")
# ]
# 
# comparison_df

"""#Step 2: Find the Country with the Highest Ratio"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# highest_ratio_country <- comparison_df[
#   which.max(comparison_df$Confirmed..population..),
# ]
# 
# highest_ratio_country

"""#Step 3: Display the Result"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cat(
#   "Country with the higher confirmed-to-population ratio:",
#   highest_ratio_country$Country.or.region,
#   "\n"
# )
# 
# cat(
#   "Ratio:",
#   round(as.numeric(highest_ratio_country$Confirmed..population..), 4)
# )

"""#Alternative Using dplyr"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# highest_ratio_country <- comparison_df %>%
#   arrange(desc(Confirmed..population..)) %>%
#   slice(1)
# 
# highest_ratio_country

"""#Interpretation

The United States has a larger proportion of confirmed COVID-19 cases relative to its population than India in the dataset. Therefore, based on the reported data, the United States shows a higher recorded infection prevalence. However, this metric should be interpreted carefully because differences in testing rates, reporting practices, demographics, and public health policies can influence the observed ratio.

#TASK 10: Find countries with confirmed to population ratio rate less than a threshold


The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

#Step 1: Define the Threshold
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# threshold <- 0.01

"""# Step 2: Filter Countries Below the Threshold

Using base R:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# low_risk_countries <- covid_df[
#   covid_df$Confirmed..population.. < threshold,
#   c("Country.or.region",
#     "Confirmed..population..")
# ]
# 
# low_risk_countries

"""#Step 3: Sort by Ratio (Ascending)"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# low_risk_countries <- low_risk_countries[
#   order(low_risk_countries$Confirmed..population..),
# ]
# 
# head(low_risk_countries)

"""#Step 4: Count the Number of Countries"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# num_countries <- nrow(low_risk_countries)
# 
# cat(
#   "Number of countries with confirmed/population ratio below 1%:",
#   num_countries
# )

"""#Step 5: Display the Results"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# print(low_risk_countries)

"""#Alternative Using dplyr"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# low_risk_countries <- covid_df %>%
#   filter(Confirmed..population.. < 0.01) %>% # Corrected column name
#   select(
#     Country.or.region,
#     Confirmed..population..
#   ) %>%
#   arrange(Confirmed..population..)
# 
# low_risk_countries

"""#Export the Results"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# write.csv(
#   low_risk_countries,
#   "countries_below_1_percent_ratio.csv",
#   row.names = FALSE
# )

"""#Interpretation

Countries with a Confirmed-to-Population Ratio below 1% have reported fewer confirmed COVID-19 cases relative to their population size.

A ratio below 1% may suggest:

Lower reported infection prevalence.
Effective containment measures.
Lower population exposure.
Differences in testing or reporting practices.

Therefore, while these countries may appear to have relatively lower COVID-19 impact based on confirmed cases, the ratio should be interpreted alongside testing coverage and reporting quality.
"""